# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'config.ru'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# redirect_to xxx and return のイディオムを維持したい
Style/AndOr:
  EnforcedStyle: conditionals

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# * 同名のメソッドがある場合にローカル変数に `_` を付ける
# * 一時変数として `_` を付ける
# というテクニックは頻出する
Lint/UnderscorePrefixedVariableName:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# 「and」「or」の使用を許可
AndOr:
  Enabled: false

# 複数行の改行はインデントに合わせる
AlignParameters:
  EnforcedStyle: with_fixed_indentation

# 1行の最大文字数を緩和
Metrics/LineLength:
  Max: 100

# メソッドの複雑度判定を多少ゆるくする
Metrics/AbcSize:
  Max: 30

# 6 は強すぎるので緩める
Metrics/CyclomaticComplexity:
  Max: 10

# * 警告 120文字
# * 禁止 160文字
# のイメージ
Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

# 20 行超えるのは migration ファイル以外滅多に無い
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

# 分岐の数。ガード句を多用しているとデフォルト 7 だと厳しい
Metrics/PerceivedComplexity:
  Max: 8
