# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a42f8413a85df25283b6e3b98c47fa8c166dd1269b23676868bfad7b11754d05eca6e84b02842daa68b958ec6c5082e88e85ffc8c94e3c6dbc64c2fa895923b8

test:
  secret_key_base: 10be3e321e72113cf6d50936297b6062febd933aa02b349c3d233b0260fac2e1eda2357da89563e6ea176e0be97c1fffeb06a5dbf7e78f5eec9784434cd554ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
